version: '3'

services:
  redis-node-1-storage1:
    image: redis:latest
    hostname: redis-node-1-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2-storage1:
    image: redis:latest
    hostname: redis-node-2-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-3-storage1:
    image: redis:latest
    hostname: redis-node-3-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-4-storage1:
    image: redis:latest
    hostname: redis-node-4-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-5-storage1:
    image: redis:latest
    hostname: redis-node-5-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-6-storage1:
    image: redis:latest
    hostname: redis-node-6-storage1
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-storage1-creator:
    image: redis:latest
    command: redis-cli --cluster create redis-node-1-storage1:6379 redis-node-2-storage1:6379 redis-node-3-storage1:6379 redis-node-4-storage1:6379 redis-node-5-storage1:6379 redis-node-6-storage1:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1-storage1
      - redis-node-2-storage1
      - redis-node-3-storage1
      - redis-node-4-storage1
      - redis-node-5-storage1
      - redis-node-6-storage1

  distributed_storage_node_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_1
    ports:
      - "1234:1234"
    expose:
      - 1234
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
      - OTHER_NODE_PORT=2
      - REDIS_SUFFIX=-storage1
    command: poetry run python3 distributed_storage/main.py
    depends_on:
      - redis-cluster-storage1-creator



  redis-node-1-storage2:
    image: redis:latest
    hostname: redis-node-1-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-2-storage2:
    image: redis:latest
    hostname: redis-node-2-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-3-storage2:
    image: redis:latest
    hostname: redis-node-3-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-4-storage2:
    image: redis:latest
    hostname: redis-node-4-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-5-storage2:
    image: redis:latest
    hostname: redis-node-5-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-node-6-storage2:
    image: redis:latest
    hostname: redis-node-6-storage2
    volumes:
      - ./redis-cluster/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf

  redis-cluster-storage2-creator:
    image: redis:latest
    command: redis-cli --cluster create redis-node-1-storage2:6379 redis-node-2-storage2:6379 redis-node-3-storage2:6379 redis-node-4-storage2:6379 redis-node-5-storage2:6379 redis-node-6-storage2:6379 --cluster-replicas 1 --cluster-yes
    depends_on:
      - redis-node-1-storage2
      - redis-node-2-storage2
      - redis-node-3-storage2
      - redis-node-4-storage2
      - redis-node-5-storage2
      - redis-node-6-storage2

  distributed_storage_node_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_2
    ports:
      - "1235:1234"
    expose:
      - 1234
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
      - OTHER_NODE_PORT=1
      - REDIS_SUFFIX=-storage2
    command: poetry run python3 distributed_storage/main.py
    depends_on:
      - redis-cluster-storage2-creator
