version: '3'

services:
  distributed_storage_node_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_1
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=.
    command: poetry run python distributed_storage/main.py 1234 12345 22345
    network_mode: host

  distributed_storage_node_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_2
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=.
    command: poetry run python distributed_storage/main.py 2234 22345 12345
    network_mode: host