services:
  distributed_storage_node_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_1
    expose:
      - 1234 
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
    command: poetry run python3 distributed_storage/main.py 2

  distributed_storage_node_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_2
    expose:
      - 1234 
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
    command: poetry run python3 distributed_storage/main.py 1

  # client_node:
  #   build: .
  #   # container_name: client_node 
  #   environment:
  #     - NODE_ADDRESS=distributed_storage_node_1:1234
  #   depends_on:
  #     - distributed_storage_node_1
  #     - distributed_storage_node_2
  #   command: poetry run python3 distributed_storage/client.py


