services:
  distributed_storage_node_1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_1
    ports:
      - 1234:1234
    expose:
      - 1234
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
      - OTHER_NODE_PORT=2
    command: poetry run python3 distributed_storage/main.py

  distributed_storage_node_2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: distributed_storage_node_2
    ports:
      - 1235:1234
    expose:
      - 1234
      - 12345
    environment:
      - GRPC_PORT=1234
      - XMLRPC_PORT=12345
      - OTHER_NODE_PORT=1
    command: poetry run python3 distributed_storage/main.py




